font_family Iosevka Nerd Font
bold_font auto
italoc_font auto
bold_italoc_font auto
font_size 13.0


#linux_display_server x11

hide_auto_decorations yes
hide_window_decorations yes
window_padding_width 10
inactive_text_alpha 0.85

remember_window_size yes
initial_window_width 800
initial_window_height 400

tab_bar_edge top
tab_bar_style powerline
tab_bar_min_tabs 1

env TERM=xterm-256color
