[symlinks]
"fish/aliases/aliases.fish" = "/home/disbelieff/.config/fish/aliases/aliases.fish"
"fish/config.fish" = "/home/disbelieff/.config/fish/config.fish"
"k9s/aliases.yaml" = "/home/disbelieff/.config/k9s/aliases.yaml"
"k9s/config.yaml" = "/home/disbelieff/.config/k9s/config.yaml"
"k9s/skins/kanagawa.yaml" = "/home/disbelieff/.config/k9s/skins/kanagawa.yaml"
"kitty/kitty.conf" = "/home/disbelieff/.config/kitty/kitty.conf"

[templates]
