[symlinks]
"fastfetch/config.jsonc" = "/home/disbelieff/.config/fastfetch/config.jsonc"
"fish/aliases/aliases.fish" = "/home/disbelieff/.config/fish/aliases/aliases.fish"
"fish/config.fish" = "/home/disbelieff/.config/fish/config.fish"
"git/.gitconfig" = "/home/disbelieff/.gitconfig"
"k9s/aliases.yaml" = "/home/disbelieff/.config/k9s/aliases.yaml"
"k9s/config.yaml" = "/home/disbelieff/.config/k9s/config.yaml"
"k9s/skins/kanagawa.yaml" = "/home/disbelieff/.config/k9s/skins/kanagawa.yaml"
"kitty/kitty.conf" = "/home/disbelieff/.config/kitty/kitty.conf"
"zed/settings.json" = "/home/disbelieff/.config/zed/settings.json"

[templates]
