[helpers]

[default]
depends = []

[default.files]
"fish/aliases" = "~/.config/fish/aliases"
"fish/config.fish" = "~/.config/fish/config.fish"
"fish/functions/sup.fish" = "~/.config/fish/functions/sup.fish"
"fish/functions/gs.fish" = "~/.config/fish/functions/gs.fish"
"fish/functions/gsl.fish" = "~/.config/fish/functions/gsl.fish"
"fish/functions/csql.fish" = "~/.config/fish/functions/csql.fish"
"fish/functions/gsmc.fish" = "~/.config/fish/functions/gsmc.fish"
"kitty/kitty.conf" = "~/.config/kitty/kitty.conf"
"k9s/aliases.yaml" = "~/.config/k9s/aliases.yaml"
"k9s/config.yaml" = "~/.config/k9s/config.yaml"
"k9s/skins" = "~/.config/k9s/skins"
"fastfetch/config.jsonc" = "~/.config/fastfetch/config.jsonc"
"zed/settings.json" = "~/.config/zed/settings.json"
"zed/keymap.json" = "~/.config/zed/keymap.json"
"git/.gitconfig" = "~/.gitconfig"
"git/identity-github" = "~/.config/git/identity-github"
"git/identity-is" = "~/.config/git/identity-is"
"git/identity-mq" = "~/.config/git/identity-mq"
"ghostty/config" = "~/.config/ghostty/config"
"opencode/config.json" = "~/.config/opencode/config.json"
"opencode/tui.json" = "~/.config/opencode/tui.json"
[settings]
default_target_type = "automatic"
